export const MAP_POINTS  = [
    {
      id: "topic1",
      name: "The port of Kaltis",
      xPercent: 90,
      yPercent: 32,
      isUnlocked: false,
      description: "",
      video: "",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "gfg",
      name: "The Inn of the Forgotten",
      xPercent: 35,
      yPercent: 45,
      isUnlocked: false,
      description: "",
      video: "",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "topfgfdgic2",
      name: "The Old School",
      xPercent: 49,
      yPercent: 55,
      isUnlocked:false,
      description: "",
      video: "",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "fdgdfgfd",
      name: "The Dravokar lineage",
      xPercent: 76,
      yPercent: 17,
      isUnlocked: false,
      description: "",
      video: "",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "topifgfgdfc2",
      name: "The Swamp Tower",
      xPercent: 65,
      yPercent: 28,
      isUnlocked:false,
      description: "",
      video: "",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "topifdgfdgc2",
      name: "The Hollow of the lost",
      xPercent: 8,
      yPercent: 37,
      isUnlocked: false,
      description: "",
      video: "",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "topicfgfd2",
      name: "Valley of Wounds",
      xPercent: 45,
      yPercent: 35,
      isUnlocked: false,
      description: "",
      video: "",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "topicfg2",
      name: "Ethrael",
      xPercent: 61,
      yPercent: 60,
      isUnlocked:false,
      description: "",
      video: "",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    
    {
      id: "topicsss2",
      name: "City of the Dead",
      xPercent: 48,
      yPercent: 17,
      isUnlocked: false,
      description: "",
      video: "",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },

  ];