export const MAP_POINTS  = [
    {
      id: "0",
      name: "The port of Kaltis",
      mapPointName:"The port of Kaltis",
      xPercent: 90,
      yPercent: 32,
      isUnlocked: false,
      description: "El largo vuaje de los acólitos termina en la espectacular ciudad de Kaltis",
      video: "./videos/locations/kaltis.mp4",
      image: "./images/locations/kaltis.png",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "1",
      name: "The Inn of the Forgotten",
      mapPointName:"The Inn of the Forgotten",
      xPercent: 85,
      yPercent: 40,
      isUnlocked: false,
      description: "En una posada iluminada por antorchas, cuatro pociones burbujean suavemente sobre una mesa. El Maestro de la Posada, guardián de viejas tradiciones, reta al héroe a un juego de memoria ancestral: las Pociones de Simon. Una a una, las pociones se encenderán siguiendo un patrón secreto. El héroe deberá reproducir la secuencia exacta o sufrir el amargo sabor de la derrota.",
      video: "./videos/locations/forgotten.mp4",
      image: "./images/locations/forgotten.png",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "2",
      name: "The Old School",
      mapPointName:"The Old School",
      xPercent: 49,
      yPercent: 55,
      isUnlocked:false,
      description: "Tras el arribo a las tierras sagradas de Kaotika, el héroe recibe su primer pergamino sagrado: el “First Scroll”. En él se revelan las instrucciones para invocar el Portal de Entrada, personalizar el sello del aventurero y, mediante magia ancestral conocida como Firebase, jurar lealtad para acceder al Reino.Para que el Portal de Entrada permanezca abierto y seguro, el guardián debe controlar el fuego sagrado en las profundidades del servidor. Mediante la validación de los sellos mágicos (tokens), los aventureros serán reconocidos y su estado será vigilado. Solo aquellos que juren lealtad y sean aceptados podrán cruzar y prosperar en Kaotika.",
      video: "./videos/locations/school.mp4",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "3",
      name: "Angelo's Laboratory",
      mapPointName:"Angelo's Laboratory",
      xPercent: 70,
      yPercent: 80,
      isUnlocked:false,
      description: "En las cámaras profundas de la Biblioteca Arcana yace el Codex of Roles, un tomo ancestral que dicta la senda de cada ser que entra en Kaotika. Cuando un aventurero cruza el fuego sagrado de la autenticación, su esencia es registrada en la colección de jugadores. Si ya existe, el códice no lo repite; si es nuevo, se graba su nombre y rol. Así, los acólitos, villanos y grandes maestros como Istvan o Mortimer son reconocidos por el Reino y conducidos hacia su propio destino, enfrentándose a los senderos que solo su rol les permite recorrer. El villano Zárate intentará sabotear tus avances.",
      video: "./videos/locations/laboratory.mp4",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "4",
      name: "Aivan's Chest",
      mapPointName:"Aivan's Chest",
      xPercent: 38,
      yPercent: 68,
      isUnlocked: false,
      description: "En los oscuros pasillos del castillo, Aivan, cargado de oro y miedo a perderlo, protege su cofre con artes arcanas. Sus manos ya no pueden alzarlo ni abrirlo, y por ello invoca un mecanismo encantado que obedezca la proximidad de quien ose acercarse.",
      video: "./videos/locations/chest.mp4",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "5",
      name: "The Swamp Tower",
      mapPointName:"The Swamp Tower",
      xPercent: 65,
      yPercent: 28,
      isUnlocked:false,
      description: "Tras descubrir un nuevo punto en el mapa, los acólitos hallan la Ciénaga, lugar embrujado donde yacen antiguos artefactos. Solo los acólitos, guiados por Mortimer, pueden ver y recogerlos, mientras el resto de roles observa sus movimientos desde la distancia.",
      video: "./videos/locations/tower.mp4",
      image: "./locations/swamp.png",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "6",
      name: "The Arcane Artifacts",
      mapPointName:"The Arcane Artifacts",
      xPercent: 65,
      yPercent: 28,
      isUnlocked:false,
      description: "",
      video: "./videos/locations/arcane.mp4",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "7",
      name: "The Hollow of the lost",
      mapPointName:"The Hollow of the lost",
      xPercent: 8,
      yPercent: 37,
      isUnlocked: false,
      description: "Deep within The Hollow of the Lost, shadows whisper forgotten names, and the spirits of those who wandered astray linger, seeking the light they were denied.",
      video: "./videos/locations/hollow.mp4",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "8",
      name: "Valley of Wounds",
      mapPointName:"Valley of Wounds",
      xPercent: 45,
      yPercent: 35,
      isUnlocked: false,
      description: "",
      video: "./videos/locations/wounds.mp4",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    {
      id: "9",
      name: "Ethrael",
      mapPointName:"Ethrael",
      xPercent: 61,
      yPercent: 60,
      isUnlocked:false,
      description: "",
      video: "https://youtu.be/HF698NLlqkk",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },
    
    {
      id: "10",
      name: "City of the Dead",
      mapPointName:"City of the Dead",
      xPercent: 48,
      yPercent: 17,
      isUnlocked: false,
      description: "",
      video: "./videos/locations/city.mp4",
      image: "",
      blockedSkills: [],
      exp: 100,
      gold: 100
    },

  ];

  